/*

Author: William Cunningham
Date  : 03/19/2026

Description:
    Package for packet types
*/

package packet_pkg;

parameter int ADDRESS_BITS = 32;

parameter int PAYLOAD_BITS = 64;

// TODO(wrcunnin): What's the best way to have this?
//  This needs to be equal to the max DEPTH_BITS of all
//  the FIFO router instances. Maybe we just set this to
//  32 for simulation and fine tune it for synthesis?
parameter int ID_BITS = 32;

typedef logic [ADDRESS_BITS-1:0] addr_t;

typedef logic [PAYLOAD_BITS-1:0] payload_t;

typedef logic [ID_BITS-1:0] id_t;

// Used by FIFO routers to prepackage data, i.e. before going out
// onto the network, or to initialize requests
typedef struct packed {
    `ifndef SYNTHESIS
    logic [30:0] padding;
    `endif

    // Determines if packet is writing or reading
    logic wen;

    // ID within FIFO for packet
    id_t id;

    // Address packet is going to
    addr_t addr;

    // Payload for the packet
    payload_t payload;
} packet_t;

typedef struct packed {
    // Indicates if a packet was a request or reponse
    // - Request is a packet generated by an external write
    // - Reponse is a packet generated by a request packet
    logic request;

    // Address of the router where packet originated from
    addr_t start_addr;

    // Packet data/information
    packet_t packet;
} net_packet_t;

parameter NET_PACKET_BITS = $bits(net_packet_t);

endpackage