// Auto-generated by LibreLane
module fifo_basic_w81_d16(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input CLK,
  input nRST,
  input ren,
  input wen,
  output[80:0] rdata,
  input[80:0] wdata,
  output full,
  output empty
);
endmodule
